development:
  adapter: postgresql
  host: localhost
  database: opendata_development
  username: opendata
  password: 
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: opendata_test
  username: opendata
  password: 
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: opendata_production
  username: opendata
  password: 
  encoding: UTF8
  pool: 5
  timeout: 5000
